### ISSUE TITLE
KotlinGrammarAntlrKotlinParser very slow for files with json-strings

### ISSUE THREAD

**Issue by fab1an** [kotlinx/ast#50] opened 2021-10-08 09:04 UTC
Creating a file like this:

````kotlin
package testpackage.

val LARGE_JSON = """
     <very large json with 77000 lines>
"""
````

Running
````kotlin
val source = AstSource.String("", stringSource)
val kotlinFile = KotlinGrammarAntlrKotlinParser.parseKotlinFile(source)
````

takes very long on a file like this. If I replace the JSON in the string with base64, it will be much faster.
Does the grammar somehow inspect the braces inside the templating?

**Comment by drieks** [comment] 2021-12-14 21:59
Duplicate of #3

**Closed by drieks** 2021-12-14 21:59 UTC
